stages:
  - test
  - build
  - internal_publish
  - mirror
  - release_publish

include:
  # Unit testing
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/unittesting@0.2.1
    inputs:
      stage: test
  # Build and publish the package
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/build_package@0.2.1
    inputs:
      job_name: build_package
      stage: build
  # Publish RC internally
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/publish_package@0.2.1
    inputs:
      job_name: publish_package_rc
      stage: internal_publish
  # Build and release package
  - component: $CI_SERVER_FQDN/bioinformatics/pipelines/python/publish_package@0.2.1
    inputs:
      job_name: publish_package_pr
      username: oauth2
      password: $PUBLISH_TOKEN
      publish_url: ${CI_API_V4_URL}/projects/4682/packages/pypi
      stage: release_publish



# Mirror master/main code to GitHub rc-0 branch
mirror_to_github:
  stage: mirror
  image: bitnami/git:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
  script:
    - git config user.name "GitLab Mirror Bot"
    - git config user.email "ci-bot@yourdomain.com"
    - git remote add github "https://x-access-token:${GITHUB_MIRROR_TOKEN}@github.com/rivm-syso/${CI_PROJECT_NAME}.git" 
    - git push --force github HEAD:refs/heads/rc-0


# Define rules for the job
build_package:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+(-rc\.\d+)?$/
publish_package_rc:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+-rc\.\d+$/
publish_package_pr:
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/
